kind = "web"
previewPath = "/"
title = "Gestão Estoque CDD Maceió"
version = "1.0.0"
id = "artifacts/estoque-cdd"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19364

[services.development]
run = "pnpm --filter @workspace/estoque-cdd run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/estoque-cdd", "run", "build" ]
publicDir = "artifacts/estoque-cdd/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19364"
BASE_PATH = "/"
